# permissions for end users to view fsdbpvs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: fsdbpv-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: fsdb
    app.kubernetes.io/part-of: fsdb
    app.kubernetes.io/managed-by: kustomize
  name: fsdbpv-viewer-role
rules:
- apiGroups:
  - fsdb.database.domain
  resources:
  - fsdbpvs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fsdb.database.domain
  resources:
  - fsdbpvs/status
  verbs:
  - get
